### ISSUE TITLE
How to adapt this gem to an existing rails project without blowing up?

### ISSUE THREAD

**Issue by PikachuEXE** [jeremyevans/ruby-refrigerator#2]
Thanks for writing this gem :)

I can only think of adding an initializer file.
But it fails as expected :P
So it would be good to have some guidance for using this gem in a rails project.

If you wish to discuss in another place (like gitter) let me know :P

=== Off topic ===
In README:
```
For example, tilt (the ruby template library) modifies BasicObject at runtime as part of template compilation.
```
It might depend on Ruby version soon (committed 5 days ago):
https://github.com/rtomayko/tilt/commit/448b12e4bd1a230bad56f183b433050edc492c00

**Comment by jeremyevans** [comment]
You would need to use `Refrigerator.freeze_core` after everything has fully loaded (all files required).  I'm guessing the best place for this in a rack application would be near the end of `config.ru`.  I've never tried this with Rails, though, so I'm not sure if that's the best place in Rails, or even if this works in Rails at all.

I'm definitely open to adding more detail to the README, if you can find a good way to get this working in Rails.

I know that tilt was fixed, after all, I'm the person who fixed it.  I'll remove that section from the README once a new tilt gem is released.

We can continue discussion here since refrigerator doesn't currently have a more appropriate forum.  If refrigerator gets popular, I'll consider adding an IRC channel or Google Group for it.

**Comment by PikachuEXE** [comment]
Will try it on `config.ru` later :)

**Comment by PikachuEXE** [comment]
Works fine by putting the call at the end
But I want to try it with the next release of `tilt` :)

**Comment by zw963** [comment]
I know this gem from roda-sequel-stack, and following configuration works with me.

```rb
if ENV['RACK_ENV'] == 'development'
  require 'pry-rescue/rack'
  # Roda.use PryRescue::Rack
  run ->(env) { App.call(env) }
else
  run App.freeze.app
  Refrigerator.freeze_core(:except=>[ 'Object'])
end
```

Though, i must exclude Gem and Object class to let my app start correct on remote production server minimum environment.

Following is backtrace:

```
bundler: failed to load command: rackup (/home/deployer/apps/marketbet_crawler_production/shared/bundle/ruby/3.0.0/bin/rackup)
/home/deployer/.rvm/rubies/ruby-3.0.2/lib/ruby/3.0.0/psych/versions.rb:3:in `<top (required)>': can't modify frozen #<Class:Object>: Object (FrozenError)
        from /home/deployer/apps/marketbet_crawler_production/shared/bundle/ruby/3.0.0/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require'
        from /home/deployer/apps/marketbet_crawler_production/shared/bundle/ruby/3.0.0/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require'
        from /home/deployer/.rvm/rubies/ruby-3.0.2/lib/ruby/3.0.0/psych.rb:2:in `<top (required)>'
        from /home/deployer/apps/marketbet_crawler_production/shared/bundle/ruby/3.0.0/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require'
        from /home/deployer/apps/marketbet_crawler_production/shared/bundle/ruby/3.0.0/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require'
        from /home/deployer/.rvm/rubies/ruby-3.0.2/lib/ruby/3.0.0/yaml.rb:4:in `<top (required)>'
        from /home/deployer/apps/marketbet_crawler_production/shared/bundle/ruby/3.0.0/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require'
        from /home/deployer/apps/marketbet_crawler_production/shared/bundle/ruby/3.0.0/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require'
        from /home/deployer/apps/marketbet_crawler_production/shared/bundle/ruby/3.0.0/gems/puma-5.3.2/lib/puma/state_file.rb:3:in `<top (required)>'
        from /home/deployer/apps/marketbet_crawler_production/shared/bundle/ruby/3.0.0/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require'
        from /home/deployer/apps/marketbet_crawler_production/shared/bundle/ruby/3.0.0/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require'
        from /home/deployer/apps/marketbet_crawler_production/shared/bundle/ruby/3.0.0/gems/puma-5.3.2/lib/puma/launcher.rb:117:in `write_state'
        from /home/deployer/apps/marketbet_crawler_production/shared/bundle/ruby/3.0.0/gems/puma-5.3.2/lib/puma/cluster.rb:398:in `run'
        from /home/deployer/apps/marketbet_crawler_production/shared/bundle/ruby/3.0.0/gems/puma-5.3.2/lib/puma/launcher.rb:181:in `run'
        from /home/deployer/apps/marketbet_crawler_production/shared/bundle/ruby/3.0.0/gems/puma-5.3.2/lib/rack/handler/puma.rb:72:in `run'
        from /home/deployer/apps/marketbet_crawler_production/shared/bundle/ruby/3.0.0/gems/rack-2.2.3/lib/rack/server.rb:327:in `start'
        from /home/deployer/apps/marketbet_crawler_production/shared/bundle/ruby/3.0.0/gems/rack-2.2.3/lib/rack/server.rb:168:in `start'
        from /home/deployer/apps/marketbet_crawler_production/shared/bundle/ruby/3.0.0/gems/rack-2.2.3/bin/rackup:5:in `<top (required)>'
        from /home/deployer/apps/marketbet_crawler_production/shared/bundle/ruby/3.0.0/bin/rackup:23:in `load'
        from /home/deployer/apps/marketbet_crawler_production/shared/bundle/ruby/3.0.0/bin/rackup:23:in `<top (required)>'
        from /home/deployer/.rvm/gems/ruby-3.0.2/gems/bundler-2.2.22/lib/bundler/cli/exec.rb:63:in `load'
        from /home/deployer/.rvm/gems/ruby-3.0.2/gems/bundler-2.2.22/lib/bundler/cli/exec.rb:63:in `kernel_load'
        from /home/deployer/.rvm/gems/ruby-3.0.2/gems/bundler-2.2.22/lib/bundler/cli/exec.rb:28:in `run'
        from /home/deployer/.rvm/gems/ruby-3.0.2/gems/bundler-2.2.22/lib/bundler/cli.rb:474:in `exec'
        from /home/deployer/.rvm/gems/ruby-3.0.2/gems/bundler-2.2.22/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
        from /home/deployer/.rvm/gems/ruby-3.0.2/gems/bundler-2.2.22/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
        from /home/deployer/.rvm/gems/ruby-3.0.2/gems/bundler-2.2.22/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
        from /home/deployer/.rvm/gems/ruby-3.0.2/gems/bundler-2.2.22/lib/bundler/cli.rb:30:in `dispatch'
        from /home/deployer/.rvm/gems/ruby-3.0.2/gems/bundler-2.2.22/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
        from /home/deployer/.rvm/gems/ruby-3.0.2/gems/bundler-2.2.22/lib/bundler/cli.rb:24:in `start'
        from /home/deployer/.rvm/gems/ruby-3.0.2/gems/bundler-2.2.22/exe/bundle:49:in `block in <top (required)>'
        from /home/deployer/.rvm/gems/ruby-3.0.2/gems/bundler-2.2.22/lib/bundler/friendly_errors.rb:128:in `with_friendly_errors'
        from /home/deployer/.rvm/gems/ruby-3.0.2/gems/bundler-2.2.22/exe/bundle:37:in `<top (required)>'
        from /home/deployer/.rvm/gems/ruby-3.0.2/bin/bundle:23:in `load'
        from /home/deployer/.rvm/gems/ruby-3.0.2/bin/bundle:23:in `<main>'

```

I don't sure about what cause this, maybe zeitwerk, puma, rack? anyway, should we mention this on our README? @jeremyevans

**Comment by zw963** [comment]
I have another question about this gem, what is the main purpose to use this gem?  performance or safety?

**Comment by jeremyevans** [comment]
The purpose of this gem is to make sure that nothing is modifying the core classes at runtime (so, safety).  Unless classes have been specifically designed for it, freezing them will not make them faster.

In terms of fixing the issue causing the backtrace, try requiring yaml before freezing the core.

**Comment by zw963** [comment]
> In terms of fixing the issue causing the backtrace, try requiring yaml before freezing the core.

I guess it cause by puma, it will load somethings use yaml after start rack server from config.ru.
