### ISSUE TITLE
Need help with tilt/erubi

### ISSUE THREAD

**Issue by AlexeyMatskevich** [jeremyevans/ruby-refrigerator#4]
I am using a roda based project like roda-sequel-stack and recently hooked up tilt and added some erb views.
An error occurs when the refrigerator is turned on:
```ruby
<FrozenError: can't modify frozen #<Class:Object>: Object>

[ 0] "/usr/local/bundle/gems/erubi-1.9.0/lib/erubi.rb:3:in `<top (required)>'",
[ 1] "/usr/local/bundle/gems/elastic-apm-3.10.1/lib/elastic_apm/spies.rb:91:in `require'",
[ 2] "/usr/local/bundle/gems/elastic-apm-3.10.1/lib/elastic_apm/spies.rb:91:in `require'",
[ 3] "/usr/local/bundle/gems/tilt-2.0.10/lib/tilt/erubi.rb:2:in `<top (required)>'",
[ 4] "/usr/local/bundle/gems/elastic-apm-3.10.1/lib/elastic_apm/spies.rb:91:in `require'",
[ 5] "/usr/local/bundle/gems/elastic-apm-3.10.1/lib/elastic_apm/spies.rb:91:in `require'",
[ 6] "/usr/local/bundle/gems/tilt-2.0.10/lib/tilt/mapping.rb:243:in `block in lazy_load'",
[ 7] "/usr/local/bundle/gems/tilt-2.0.10/lib/tilt/mapping.rb:241:in `each'",
[ 8] "/usr/local/bundle/gems/tilt-2.0.10/lib/tilt/mapping.rb:241:in `lazy_load'",
[ 9] "/usr/local/bundle/gems/tilt-2.0.10/lib/tilt/mapping.rb:216:in `lookup'",
[10] "/usr/local/bundle/gems/tilt-2.0.10/lib/tilt/mapping.rb:154:in `,
[11] "/usr/local/bundle/gems/tilt-2.0.10/lib/tilt/mapping.rb:137:in `new'",
[12] "/usr/local/bundle/gems/tilt-2.0.10/lib/tilt.rb:43:in `new'",
[13] "/usr/local/bundle/gems/roda-3.37.0/lib/roda/plugins/render.rb:251:in `initialize'",
[14] "/usr/local/bundle/gems/roda-3.37.0/lib/roda/plugins/render.rb:595:in `new'",
[15] "/usr/local/bundle/gems/roda-3.37.0/lib/roda/plugins/render.rb:595:in `block in retrieve_template'",
[16] "/usr/local/bundle/gems/roda-3.37.0/lib/roda/plugins/render.rb:504:in `cached_template'",
[17] "/usr/local/bundle/gems/roda-3.37.0/lib/roda/plugins/render.rb:577:in `retrieve_template'",
[18] "/usr/local/bundle/gems/roda-3.37.0/lib/roda/plugins/render.rb:366:in `render'",
[19] "/usr/local/bundle/gems/roda-3.37.0/lib/roda/plugins/render.rb:400:in `view'",
[20] "/usr/local/bundle/gems/rodauth-2.4.0/lib/rodauth/features/base.rb:751:in `_view'",
[21] "/usr/local/bundle/gems/rodauth-2.4.0/lib/rodauth/features/base.rb:373:in `view'",
[22] "/usr/local/bundle/gems/rodauth-2.4.0/lib/rodauth/features/jwt.rb:142:in `view'",
[23] "/usr/local/bundle/gems/rodauth-2.4.0/lib/rodauth.rb:187:in `block in view'",
[24] "/app/routes/rodauth.rb:69:in `block (2 levels) in <class:Idp>'",
[25] "/usr/local/bundle/gems/rodauth-2.4.0/lib/rodauth.rb:206:in `before_login_route'",
[26] "/usr/local/bundle/gems/rodauth-2.4.0/lib/rodauth/features/login.rb:28:in `block (2 levels) in <module:Rodauth>'",
[27] "/usr/local/bundle/gems/rodauth-2.4.0/lib/rodauth.rb:124:in `block (2 levels) in route'",
[28] "/usr/local/bundle/gems/roda-3.37.0/lib/roda/request.rb:564:in `if_match'",
[29] "/usr/local/bundle/gems/roda-3.37.0/lib/roda/request.rb:169:in `is'",
[30] "/usr/local/bundle/gems/rodauth-2.4.0/lib/rodauth.rb:121:in `block in route'",
[31] "/usr/local/bundle/gems/rodauth-2.4.0/lib/rodauth/features/base.rb:152:in `route!'",
[32] "/usr/local/bundle/gems/rodauth-2.4.0/lib/rodauth.rb:349:in `rodauth'",
[33] "/app/routes/rodauth.rb:200:in `block in <class:Idp>'",
[34] "/usr/local/bundle/gems/roda-3.37.0/lib/roda/plugins/hash_routes.rb:426:in `block in hash_branches'",
[35] "/usr/local/bundle/gems/roda-3.37.0/lib/roda/request.rb:499:in `always'",
[36] "/usr/local/bundle/gems/roda-3.37.0/lib/roda/plugins/hash_routes.rb:426:in `hash_branches'",
[37] "/usr/local/bundle/gems/roda-3.37.0/lib/roda/plugins/hash_routes.rb:448:in `hash_routes'",
[38] "/usr/local/bundle/gems/roda-3.37.0/lib/roda.rb:502:in `_roda_run_main_route'",
[39] "/usr/local/bundle/gems/roda-3.37.0/lib/roda/plugins/_before_hook.rb:27:in `_roda_run_main_route'",
[40] "/usr/local/bundle/gems/roda-3.37.0/lib/roda.rb:480:in `block in _roda_handle_main_route'",
[41] "/usr/local/bundle/gems/roda-3.37.0/lib/roda.rb:478:in `catch'",
[42] "/usr/local/bundle/gems/roda-3.37.0/lib/roda.rb:478:in `_roda_handle_main_route'",
[43] "/usr/local/bundle/gems/roda-3.37.0/lib/roda/plugins/error_handler.rb:87:in `_roda_handle_main_route'",
[44] "/usr/local/bundle/gems/roda-3.37.0/lib/roda.rb:366:in `block in base_rack_app_callable'",
[45] "/usr/local/bundle/gems/roda-3.37.0/lib/roda.rb:53:in `call'",
[46] "/usr/local/bundle/gems/rack-unreloader-1.7.0/lib/rack/unreloader.rb:84:in `call'",
[47] "/usr/local/bundle/gems/sentry-raven-3.1.1/lib/raven/integrations/rack.rb:51:in `call'",
[48] "/usr/local/bundle/gems/rack-attack-6.3.1/lib/rack/attack.rb:111:in `call'",
[49] "/usr/local/bundle/gems/iodine-0.7.42/lib/rack/handler/iodine.rb:13:in `start'",
[50] "/usr/local/bundle/gems/iodine-0.7.42/lib/rack/handler/iodine.rb:13:in `run'",
[51] "/usr/local/bundle/gems/iodine-0.7.42/exe/iodine:271:in `call'",
[52] "/usr/local/bundle/gems/iodine-0.7.42/exe/iodine:277:in `<top (required)>'",
[53] "/usr/local/bundle/bin/iodine:23:in `load'",
[54] "/usr/local/bundle/bin/iodine:23:in `<top (required)>'",
[55] "/usr/local/lib/ruby/2.7.0/bundler/cli/exec.rb:63:in `load'",
[56] "/usr/local/lib/ruby/2.7.0/bundler/cli/exec.rb:63:in `kernel_load'",
[57] "/usr/local/lib/ruby/2.7.0/bundler/cli/exec.rb:28:in `run'",
[58] "/usr/local/lib/ruby/2.7.0/bundler/cli.rb:476:in `exec'",
[59] "/usr/local/lib/ruby/2.7.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'",
[60] "/usr/local/lib/ruby/2.7.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'",
[61] "/usr/local/lib/ruby/2.7.0/bundler/vendor/thor/lib/thor.rb:399:in `dispatch'",
[62] "/usr/local/lib/ruby/2.7.0/bundler/cli.rb:30:in `dispatch'",
[63] "/usr/local/lib/ruby/2.7.0/bundler/vendor/thor/lib/thor/base.rb:476:in `start'",
[64] "/usr/local/lib/ruby/2.7.0/bundler/cli.rb:24:in `start'",
[65] "/usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/libexec/bundle:46:in `block in <top (required)>'",
[66] "/usr/local/lib/ruby/2.7.0/bundler/friendly_errors.rb:123:in `with_friendly_errors'",
[67] "/usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/libexec/bundle:34:in `<top (required)>'",
[68] "/usr/local/bin/bundle:23:in `load'",
[69] "/usr/local/bin/bundle:23:in `<main>'"
```
Although I saw the issue #2 It looks like the problem is not with tilt itself, but with erubi.

Any ideas how I can handle this?

**Comment by jeremyevans** [comment]
If you add `require 'tilt/erubi'` after the `require 'roda'`, does that fix it?  Note that you shouldn't need to do this, as roda-sequel-stack loads the render plugin with the :escape option, which will do the `require 'tilt/erubi'`.

**Comment by AlexeyMatskevich** [comment]
Thanks, I added a plugin and it helped, it looks like I got confused because I came to tilt with the rodauth plugin and missed the render plugin because it works without it.
